### ISSUE TITLE
Left hand traffic LHT opendrive conversion.

### ISSUE THREAD

**Issue by emchod** [CommonRoad/commonroad-scenario-designer#14]
Hello,
My goal is to convert the LHT opendrive roadnetwork to the lanelet2 format (autoware compatible). 
I'm using Python API for conversion.
Does CommonRoad support left hand traffic opendrive?
If yes, are there any specific configuration settings that need to be provided?

Many thanks for your help.

**Comment by smaierhofer** [comment]
Hi, I have never tested the conversion of a LHT road network from OpenDRIVE to CommonRoad or Lanelet2. Therefore, I don't know whether it will work. Please try it out and report if something does not work.

**Comment by hcLime** [comment]
Thanks for the quick reply!
I did test it, and unfortunately, it didn't work. Autoware still treats it as an RHT map.
If you would like to give it a go, I can provide you with a simple opendrive file describing the LHT road network.
It would be really beneficial to introduce LHT support in your tool.

**Comment by smaierhofer** [comment]
Yes, if you can provide us with an OpenDRIVE map, we can try to solve the problem.

**Comment by hcLime** [comment]
That's great.
I have attached the opendrive file below.
Many thanks

[t_junction_LHT.zip](https://github.com/CommonRoad/commonroad-scenario-designer/files/14694946/t_junction_LHT.zip)

**Comment by smaierhofer** [comment]
@emchod We integrated support for LHT. The feature will be released with version 0.8.3 and is already in the develop branch.
