### ISSUE TITLE
Lane change & speed limit attributes (lanelet2)

### ISSUE THREAD

**Issue by emchod** [CommonRoad/commonroad-scenario-designer#16]
Hi, 
I use CommonRoad tool for converting opendrive to Autoware's lanelet2 format.
I believe that CR currently does not provide a "lane_change" tag within the lanelet2 which is required for the AW system. Is this something that can be implemented?
Secondly, I have a speed limit specified in the opendrive file, which is not being converted to the lanelet2 format. Does CR convert the road speed limit?
Many thanks.

**Comment by smaierhofer** [comment]
Hi,
you're right, currently we don't support the "lane_change" tag of lanelet2.
Yes, I think this can be implemented. 
One would need to check all lanelets whether they have a solid lane marking, or a sign prohibits overtaking, etc., and assign it to the linestrings during conversion.

Speed limits should be converted. 
Can you send me the OpenDRIVE map with the speed limit via email?
Then, we could check why the speed limit wasn't considered.

**Comment by emchod** [comment]
Thank you for your response. It would be very beneficial to accommodate lane_change tag when Autoware lanelet2 configuration is required. Otherwise, the system is not able to perform lane change actions. 

Regarding the speed limit, I have sent you an email with the openDrive file as requested.

**Comment by smaierhofer** [comment]
@emchod We integrated the lane change attribute (based on the available line marking information) and the speed limit in the latest develop branch.
